services:
  app:
    image: docker-spring-boot-postgres:latest
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"

    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=compose-postgres

volumes:
  postgres_data:
