create table consultas(

    id bigint not null GENERATED BY DEFAULT AS IDENTITY,
    medico_id bigint not null,
    paciente_id bigint not null,
    data timestamp not null,
    status_consulta VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    motivo_cancelamento VARCHAR(55),
    data_cancelamento timestamp,
    observacoes VARCHAR(255),

    primary key(id),
    constraint fk_consultas_medico_id foreign key(medico_id) references medicos(id),
    constraint fk_consultas_paciente_id foreign key(paciente_id) references pacientes(id)

);